apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets  # Mounts the secret data as files in this path
      readOnly: true           # It's a good practice to mount secrets as read-only
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret  # The Secret we created earlier
